order tracking info in mobile view  proper alignment with lines.
MuzaffarMohammed/kfmenterprises-ecommerce pull request #93
Opened 2021-12-07 12:16 UTC by MohammedHabeebkhan

2021-12-08 10:00 UTC, MuzaffarMohammed requested changes
Please download the CSS file and include instead of URL

2021-12-08 10:00 UTC, MuzaffarMohammed commented on styles/orderDetails.css
> +@import url("https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css");
Please download this css and add it locally instead of url.

2021-12-09 00:24 UTC, MohammedHabeebkhan commented on styles/orderDetails.css
> +@import url("https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css");
changes has been done.

2021-12-09 16:05 UTC, MuzaffarMohammed approved these changes

2021-12-09 16:05 UTC, merged